"use client"

import React from 'react'

export default function Body() {
    return (
        <section className="pl-[300px]">
            <div className="bg-gradient-to-b from-[#ddeef5] to-gray-100 p-5 rounded-xl drop-shadow-md">
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Exercitationem unde, aliquid molestias rerum, nihil eum corporis fuga sapiente atque nemo commodi. Ullam doloremque a accusantium! Possimus asperiores impedit autem earum! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Adipisci ipsum minus esse soluta ex sequi odio voluptatum. Fugiat aperiam autem mollitia libero corrupti aliquid sapiente consectetur architecto quidem voluptatum. Nostrum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iure omnis tempore provident officiis aperiam expedita assumenda mollitia tenetur rerum quaerat in eligendi non harum modi, dolore totam, alias temporibus. Corrupti.
                    Assumenda magni ipsum ratione dolor quis nobis dolore impedit. Atque officia rem et fugit neque consequatur esse accusamus nulla labore autem repellendus adipisci asperiores, perferendis amet eligendi placeat numquam temporibus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus aliquid, perferendis minus libero culpa dicta beatae quisquam nostrum voluptates consectetur minima maiores, quaerat possimus quo vero alias tempore repudiandae maxime!
                    Assumenda voluptates ab, cupiditate placeat mollitia necessitatibus voluptatum. Inventore temporibus nesciunt fuga, ullam laboriosam veritatis molestiae Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veritatis error esse eveniet earum ab. Distinctio nobis minus cum saepe dolores praesentium iusto vero, ipsam odit facilis iure asperiores, sapiente dignissimos.
                    Ipsam non minus accusantium in eaque, nesciunt dicta quasi! A mollitia assumenda eveniet doloribus nobis cumque, nesciunt, natus quia deserunt repudiandae minima consequatur repellendus dolorum id temporibus corporis esse in. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, error! Amet fugiat placeat voluptates, totam molestias inventore reprehenderit vitae, nulla iure, illum illo maiores eaque saepe explicabo error quod consectetur.
                    Ea quibusdam excepturi laborum ex voluptatem alias nulla, consequuntur tenetur suscipit deleniti modi, dicta voluptatum aperiam numquam eaque veniam magnam vero quia perferendis perspiciatis nisi asperiores officiis ratione fugit. Recusandae.
                    Obcaecati vero saepe suscipit inventore. Voluptate dolorem mollitia provident quas esse amet, odio est eveniet voluptatibus quibusdam, illum in molestias voluptates voluptatum corrupti magnam molestiae consequatur. Harum provident sapiente ullam.
                    Distinctio laboriosam exercitationem iste animi sequi beatae dignissimos, alias obcaecati, doloribus voluptates illum praesentium cum dolore ab fuga in rerum sapiente hic, ipsa nobis ducimus quos saepe illo? Labore, vero.
                    Sunt molestiae laborum explicabo asperiores quaerat. Cupiditate molestiae, nostrum dolore, ea labore eaque aliquid reiciendis maiores unde aliquam architecto at! Ut, distinctio? Eligendi a tenetur enim nemo laudantium necessitatibus quia.
                    Excepturi blanditiis temporibus neque iusto odit optio impedit fuga, nulla rerum dolore ad asperiores autem. Quas dicta nulla tenetur quibusdam repudiandae rem. Consequuntur placeat rerum dignissimos tempore. Enim, consequatur soluta.
                    Error odio magnam natus, recusandae ipsum, provident veritatis porro sint soluta exercitationem, voluptatibus voluptatum ipsa sequi consequatur. Ullam beatae ab blanditiis explicabo asperiores rerum saepe recusandae, quibusdam voluptas inventore exercitationem.
                    Perferendis saepe doloremque expedita neque voluptate velit ullam laboriosam, qui aliquid facilis voluptatem sunt tenetur nisi doloribus, est totam molestiae? Quia reprehenderit tempore amet in consectetur ipsa facilis, accusantium odio.
                    Rem deserunt nemo doloremque neque enim eveniet magni, laudantium, accusantium placeat iste quaerat numquam! Voluptate maxime quia eos saepe delectus esse, fugit repellendus illo, eveniet minus architecto, autem quis velit!
                    Nostrum exercitationem impedit tenetur ullam! Dolor nostrum ipsam impedit aspernatur maxime ad repellat ratione rerum sunt laboriosam voluptate, doloribus commodi? Blanditiis deleniti ex nesciunt delectus aspernatur numquam hic atque provident.
                    Maxime perferendis impedit quidem mollitia quis earum voluptatum, eos atque pariatur magni molestiae, laudantium inventore neque repellendus soluta. Laborum et praesentium voluptatem eius voluptate quam vel. Officia ratione voluptas dolores?
                    Unde non, earum velit, nulla sunt molestiae tempore nihil ex voluptatibus ipsum fugiat modi sapiente qui maxime cum optio! Ratione nesciunt ad non sequi distinctio placeat cupiditate dolor iste molestiae.
                    Esse inventore corporis quod hic fugit officia, rerum in nisi eum neque saepe quia libero, blanditiis veniam dolorum dicta odio autem, dignissimos dolore voluptatem cupiditate dolor omnis ea optio. Molestiae.
                    Nostrum iste saepe libero et quae ad consectetur atque corrupti deleniti optio, in voluptatem. Obcaecati, earum ea esse architecto excepturi rerum, fugiat rem quas praesentium optio laboriosam? Harum, perferendis quisquam.
                    Laborum eius doloribus exercitationem quisquam soluta voluptas obcaecati harum expedita officiis dignissimos eum a suscipit inventore quis ipsam tempora odio accusamus deserunt in nostrum, commodi esse! Voluptas doloribus nihil fugiat?
                    Saepe soluta corrupti animi veniam. Corporis aspernatur asperiores ipsum sunt praesentium, voluptatum omnis cupiditate aut pariatur illo fugit placeat eos natus a tempore, odit hic ullam repudiandae sequi numquam perspiciatis.
                    Dignissimos delectus aut assumenda quo neque amet dolor, repellendus expedita, magnam, atque unde ratione error placeat modi laborum mollitia perspiciatis numquam quas quis! Iusto molestiae laudantium eius accusantium nostrum mollitia?
                    Alias laboriosam adipisci debitis recusandae omnis, voluptatum perspiciatis doloremque accusamus inventore, eaque voluptate ipsa id fuga quibusdam porro vitae temporibus veniam facere? Quasi, consectetur in culpa facere debitis corrupti qui!
                    Repellendus quae, rem doloremque mollitia atque consectetur repudiandae animi beatae non. Voluptatem est eos porro voluptate earum praesentium ipsum quae, rerum corporis dolore, amet perferendis. Facere eveniet laudantium in. Repudiandae.
                    Cupiditate eligendi porro odio iure esse debitis molestiae, aspernatur sunt enim nam eius impedit illum odit exercitationem, iste tenetur veritatis culpa dolore consectetur. Perspiciatis aliquam repudiandae repellendus aperiam illum iste?.</p>
            </div>
        </section>
    )
}
